name = "rust-backend"
#type = "javascript"
compatibility_date = "2024-05-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "rust_items_db"
database_id = "${D1_DB_ID}"
#database_id = "local"